# Generated by Django 5.0.4 on 2024-06-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImages',
        ),
    ]
