# Generated by Django 5.0.4 on 2024-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_profileimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='default_user/user_img.png', null=True, upload_to='profile_images/'),
        ),
    ]
