# Generated by Django 5.0.4 on 2024-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages/audios'),
        ),
        migrations.AddField(
            model_name='messages',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='messages/docs'),
        ),
        migrations.AddField(
            model_name='messages',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='messages/pictures'),
        ),
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='messages/videos'),
        ),
    ]
