# Generated by Django 5.0.4 on 2024-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_messages_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='message_type',
        ),
        migrations.AddField(
            model_name='messages',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/audio/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='docs_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/docs/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='messages/picture/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/video/'),
        ),
    ]
