# Generated by Django 5.0.4 on 2024-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_rename_audio_file_messages_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
