# Generated by Django 5.0.4 on 2024-06-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_remove_messages_audio_remove_messages_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='file',
        ),
        migrations.AddField(
            model_name='messages',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages/audio/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='messages/docs/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='messages/picture/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='messages/video/'),
        ),
    ]
